/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.Conect;
import backend.Producto;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC_Alberto
 */
public class FindVenta extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    String [] cabecera = {"Id","Nombre","Descripcion","Cliente","Fecha","Pago","P.Unit","Cantidad"};
    String [][] Datos = {}; 
    private  List <Producto> p;
    
    /**
     * Creates new form FindVenta
     */
    public FindVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Busqueda de Ventas");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Id", "Producto", "Descripcion", "Fecha", "Pago", "P.Unt", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jtabla);
        modelo = new DefaultTableModel(Datos,cabecera);
        jtabla.setModel(modelo);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(400, 200, 602, 151);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    // End of variables declaration//GEN-END:variables

 public void Insertar(){
       
      jtabla.getColumnModel().getColumn(0).setPreferredWidth(70);
      jtabla.getColumnModel().getColumn(1).setPreferredWidth(150);
      jtabla.getColumnModel().getColumn(2).setPreferredWidth(150);
      jtabla.getColumnModel().getColumn(3).setPreferredWidth(150);
      jtabla.getColumnModel().getColumn(4).setPreferredWidth(150);
      jtabla.getColumnModel().getColumn(5).setPreferredWidth(150);
      jtabla.getColumnModel().getColumn(6).setPreferredWidth(150);
      jtabla.getColumnModel().getColumn(7).setPreferredWidth(150);
      
        try {
            p = Conect.VerRVentas();
            
            int c = p.size();
            
            for(int a = 0; a < c; a++){
                
                Producto emp = p.get(a);
                
                Object[] newRow = {emp.getId()  ,emp.getNombre() ,emp.getCategoria(), emp.getCliente(),
                    emp.getDate(),emp.getCosto(),emp.getPrecio() ,emp.getCantidad()};
                modelo.addRow(newRow);    
            }
        }
      catch (SQLException ex) {
            Logger.getLogger(FindVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
  }

}
