/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.Producto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC_Alberto
 */
public class FindVenta extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    String [] cabecera = {"Id","Nombre","Descripcion","Cliente","Fecha","Precio","Cantidad"};
    String [][] Datos = {}; 
    private  List <Producto> p;
    
    /**
     * Creates new form FindVenta
     */
    public FindVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Busqueda de Ventas");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Producto", "Descripcion", "Fecha", "Pago", "P.Unt", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jtabla);
        modelo = new DefaultTableModel(Datos,cabecera);
        jtabla.setModel(modelo);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla;
    // End of variables declaration//GEN-END:variables
}
