/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Conect;
import backend.Producto;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author casa
 */
public class ModificarRegistrosP extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarRegistrosP
     */
    public ModificarRegistrosP() {
        initComponents();
        loadList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/images/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/images/nuevoProducto.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/images/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 841, 401);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String[] s= {};
        AgregarProducto.main(s);
        loadList();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
       jTextArea1.setText(productos.get(lista.getSelectedIndex()).toString());
       flag=true;
    }//GEN-LAST:event_listaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String[] s= {};
        if(flag==true)
        {
            Producto p = get((String)lista.getSelectedValue());
            ModificacionProducto.main(s,p);
            loadList();
        }
        else
        {
            Message.information(this,"Para modificar tiene que seleccionar un elemento de a modificar");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
       
    }//GEN-LAST:event_listaValueChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Producto p = get((String)lista.getSelectedValue());
        if(flag==true)
        {
            try
            {
               Conect.deleProducto(p);
               loadList();
               Message.information(this,"Elemento fue eliminado con exito");
            }catch(SQLException ex){
               Message.error(this,ex.getMessage());
            }
        }
        else
        {
            Message.information(this,"Para eliminar tiene que seleccionar un elemento de a modificar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList lista;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel modelo;
    private ArrayList<Producto> productos = null;
    private boolean flag=false;
    public void loadList()
    {
        modelo = new DefaultListModel();
        
         try
        {
            productos = Conect.findAll();
        
        }catch(SQLException ex)
        {
            Message.error(this,ex.getMessage());
        }
        for(Producto p: productos)
        {
            modelo.addElement(p.getNombre());
        }
        lista.setModel(modelo);
    }
    public Producto get(String name)
    {
        Producto p1 = null;
        for(Producto p : productos)
        {
            if(p.getNombre().equalsIgnoreCase(name))
            {
                p1=p;
                break;
            }
        }
        return p1;
    }
}
